### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by Fabrice-leterme** [Fabrice-leterme/mochadoom#1]
- [ ]  Add an easy way to add new menus
- [ ]  Create loginscreen on startup
- [ ]  Connect with a Netty gameserver
- [ ] Implement networking for multiplayer
- [ ] Achievements (server/client)
- [ ] Leveling solo/multiplayer (server/client)
